name: Extract File

on:
  workflow_dispatch:
    inputs:
      file_name:
        description: 'Nama file'
        required: true
        type: string
      destination:
        description: 'Folder tujuan'
        required: true
        type: string

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract file
        run: |
          unzip ${{ inputs.file_name }} -d ${{ inputs.destination }}
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Extracted ${{ inputs.file_name }} to ${{ inputs.destination }}"
          git push origin HEAD:${{ github.ref_name }}  # Push ke branch saat ini (misalnya main)
